### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by keizah7** [dcasia/nova-mega-filter#77]
[2022-03-09 16:39:25] local.ERROR: Trying to access array offset on value of type null {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /Users/arturas/code/Artme/wil/vendor/digital-creative/nova-mega-filter/src/HasMegaFilterTrait.php:127)
[stacktrace]
#0 /Users/arturas/code/Artme/wil/vendor/digital-creative/nova-mega-filter/src/HasMegaFilterTrait.php(127): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Trying to acces...', '/Users/arturas/...', 127)
#1 /Users/arturas/code/Artme/wil/vendor/digital-creative/nova-mega-filter/src/HasMegaFilterTrait.php(69): App\\Nova\\User->getFilterState(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest), Object(DigitalCreative\\MegaFilter\\MegaFilter))
#2 /Users/arturas/code/Artme/wil/nova/src/ResolvesFields.php(32): App\\Nova\\User->availableFields(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest))

**Comment by milewski** [comment]
Not an issue anymore on latest version
